Tags page
hydrusnetwork/hydrus pull request #1215
Opened 2022-08-19 19:15 UTC by Zweibach

A user managed to confuse themselves into thinking that Hydrus can only do huge downloads while reading the first section of the downloads page and then refused to read further. The first paragraph now explicitly spells out that Hydrus can actually do singly URL/file downloads too.

A user has created a flatpak package which is supposedly pretty universally usable by various Linux distros, that fucking bird seems to think it's nifty at least.

Wrote some additions to the tags page:
* Siblings and parents and a tl;dr of what they do
* Tag services and how they work, I think I got it mostly right
* Display rules for tag services
* The two default tag services

2022-08-19 19:25 UTC, floogulinc requested changes
Please don't remove the explicit section IDs.

2022-08-19 19:25 UTC, floogulinc commented on docs/faq.md
> -## what is a repository? { id="repositories" }
Don't remove these section IDs. They are kept to be consistent with the old docs so old links work properly.

2022-08-20 19:19 UTC, floogulinc approved these changes

2022-11-05 20:09 UTC, merged

2022-11-05 20:09 UTC, hydrusnetwork commented
Thank you!